### ISSUE TITLE
enable SSL for meteor

### ISSUE THREAD

**Issue by zdavatz** [zdavatz/remoterun#3]
https://stackoverflow.com/questions/27963749/setup-https-ssl-on-localhost-for-meteor-development

**Comment by zdavatz** [comment]
https://zerossl.com/free-ssl/#self

**Comment by zdavatz** [comment]
If I set `ssl: true` in `private/settings` then I get: 

`SSLProxy is not defined`

see below

```
W20200106-08:55:26.758(1)? (STDERR) /home/zeno/.meteor/packages/meteor-tool/.1.8.3.1psqq87.oqqe++os.linux.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.linux.x86_64/dev_bundle/server-lib/node_modules/fibers/future.js:280
W20200106-08:55:26.759(1)? (STDERR)                                             throw(ex);
W20200106-08:55:26.759(1)? (STDERR)                                             ^
W20200106-08:55:26.759(1)? (STDERR) 
W20200106-08:55:26.760(1)? (STDERR) ReferenceError: SSLProxy is not defined
W20200106-08:55:26.760(1)? (STDERR)     at server/main.js:67:5
W20200106-08:55:26.760(1)? (STDERR)     at Function.time (/home/zeno/.software/remoterun/.meteor/local/build/programs/server/profile.js:273:30)
W20200106-08:55:26.760(1)? (STDERR)     at /home/zeno/.software/remoterun/.meteor/local/build/programs/server/boot.js:412:15
W20200106-08:55:26.761(1)? (STDERR)     at /home/zeno/.software/remoterun/.meteor/local/build/programs/server/boot.js:462:7
W20200106-08:55:26.761(1)? (STDERR)     at Function.run (/home/zeno/.software/remoterun/.meteor/local/build/programs/server/profile.js:280:14)
W20200106-08:55:26.761(1)? (STDERR)     at /home/zeno/.software/remoterun/.meteor/local/build/programs/server/boot.js:460:13
```

**Comment by zdavatz** [comment]
I did do `meteor add tarang:ssl`

**Comment by zdavatz** [comment]
trying this: https://github.com/nourharidy/meteor-ssl

**Comment by zdavatz** [comment]
renaming the keys: 1114735a500e66ddb95b501c0b86ae9e3cf98f70

**Comment by zdavatz** [comment]
still getting this:

![latest-screenshot](https://user-images.githubusercontent.com/4953/71812706-2e58c600-3078-11ea-97df-5386bc1bdbf5.png)

**Comment by zdavatz** [comment]
https://github.com/nourharidy/meteor-ssl/issues/17

**Comment by zdavatz** [comment]
https://github.com/nourharidy/meteor-ssl/issues/20#issuecomment-461400971
